### PR TITLE
[WIP] Try using psi4numpy's utils for jupyter notebook tests

### PR DESCRIPTION
**Pull request by bannanc**
I'll start by seeing if the tests pass here, they pass locally.

### CODE REVIEW

**Comment by bannanc** [comment]
These passed locally after I `pip install pytest-shutil` which I'm already doing in the travis file. I think I must be missing something installed locally, still trying to figure out what it is.

**Comment by bannanc** [comment]
OK, I fixed the potentially more obvious problem that jupyter wasn't installed for the travis tests. 
I don't understand why the OE tests are failing now.

**Comment by bannanc** [comment]
OK so I'm a dummy and missed that all the OE tests were failing, there is something wrong with the license. I'm encrypting a new one right now.

**Comment by bannanc** [comment]
OK, it isn't the license itself, its that it can't be accessed from the directory that the jupyter notebook is running in. Everything else passes. I'm willing to bet that is the same reason #21 is failing too you just don't see the license error and it gets caught in the notebook.

**Comment by bannanc** [comment]
@davidlmobley @janash @dgasmith any of you used had issues accessing a license file before?

**Comment by davidlmobley** [comment]
I have not had that problem. Can you reproduce locally?

**Comment by bannanc** [comment]
I haven't tried a travis docker, but following the conda installation on a new environment on my computer works, I tried having travis make the `*.py` files in the example folder, I wander if there is a way to generate them as `test_*.py` files instead?

I haven't been able to find anything with people running into similar problems online.

**Comment by davidlmobley** [comment]
OK, I have zero experience on this and I don't think I'll get to dig in to it in the immediate future. Maybe get a second opinion from @nathanmlim , as (a) he can probably figure it out faster than me, and (b) may also benefit from being able to use the same technology...

**Comment by bannanc** [comment]
I think nbval is a better way to test notebooks, you can check that the output hasn't changed and it is more general. I merged PR #21 I'm going to close this one, but keep the branch incase something else goes wrong and we want to switch back.

**Pull request closed without merging**
