### PR TITLE
Migrate from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by mattwthompson**
- [x] Add GitHub Actions workflow to run CI
- [x] Merge #101 

Not intended to be a part of this PR
- [ ] Set up OpenEye in CI

### CODE REVIEW

**Comment by mattwthompson** [comment]
If nothing else, the status passing in the last commit (merging #101) shows that that change passes tests.

**Review by j-wags — APPROVED** [review]
LGTM - Thanks @mattwthompson. Not blocking, but I'd recommend deleting `travis.yml.bak` before merging.

**Comment by mattwthompson** [comment]
I've taken the liberty of also removing un-used scripts (largely boilerplate from the cookiecutter) and updating some of the outdated portions of the README.

**Comment by mattwthompson** [comment]
The phantom Travis CI status check is blocking my ability to merge since this is in @MobleyLab, not @openforcefield. Are you able to override the status check requirement as an administrator @j-wags? If not we'll need to ping David and/or Caitlin.

**Comment by davidlmobley** [comment]
@mattwthompson can I do something to help?

**Comment by mattwthompson** [comment]
Could you merge? This is what I see:

image

but you may have the "click here to use your administrator privileges" or something to that effect.

This is because the Travis CI check is being reported as required but is removed here. It'll probably not be an issue moving forward. I deleted the webhook, too, for good measure.

**Comment by davidlmobley** [comment]
Very weird, it's showing me the same thing. I also have not yet found the place to disable the thing which requires status checks to pass before merging. :( Investigating.

**Comment by mattwthompson** [comment]
Found it - there was a separate branch protection rule requiring that Travis CI pass (not simply a "make sure they're all green, no matter what they are"), which I manually removed.

**Comment by mattwthompson** [comment]
All done - thanks!

**Pull request merged**
