### PR TITLE
API change, major doc string update, and cleaning up READMEs

### PR DESCRIPTION
**Pull request by bannanc**
In this PR I will do minor cleaning of the README (formatting, see PR #26 for more extensive clean-up). Then I'm trying to close some more minor things from the issue tracker. Here is what is done so far:

#80 - Update badges to show which operating systems are being tested and format with logo to be less dense
#78 - use `oechem.OEChemIsLicensed()` to check for OE_LICENSE file, not just that it is installed

-----

Things I plan to address in this PR
- [x] #55 Add parameters/returns to all function doc strings
- [x] #73 Add `__str__` functions for Molecules/Atoms/Bonds
- [x] #77 I'll follow openforcefield tests to make sure example code in READMEs and Docs are being tested.
- [x] #86 make sure tests pass with jupyter notebooks
- [x] #83 change API for `ChemPerGraph` to `SingleGraph`
- [x] #84 update smirks checks to be ChemPer specific

### CODE REVIEW

**Comment by bannanc** [comment]
I know I broke things on this most recent commit, I'm hoping that looking at the diff up here will help me understand how to fix it, but I can't figure out what I changed that would affect the actual code.

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 2e0b018a1239c3ff1afd51d281cd1d119a582d1a into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-82933c8c889f9aaba67faba477a8f84c060301dc)

**new alerts:**

* 1 for \_\_init\_\_ method calls overridden method

**fixed alerts:**

* 1 for \_\_eq\_\_ not overridden when adding attributes

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging 6bd24f19fcad5671f6bf41194cb474cb0ae9a5d7 into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-b7c139affd8d6eb6a1e6536091ca92dd76d0afb9)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging abbb0f645c487fd8178ce17da54357f8ead89ab1 into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-a0ccd049a7bcdd20291fc15f5ef44a67489c5d52)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging 331689f21fdd32f15d3aa738ba267db2013197d6 into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-a2261a26ecbb5e8bfca4b877e6484ba6cb4773b2)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging a90ff4d1861c1ba7b3304da20364165b2edd4339 into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-83588b12da2b5cb0a3cc797d34d5836cec46a656)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging 8a7bdd0700e7fcdfdb9cd844b77c14e32d6737b8 into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-49112ab8401ff7002485a8e8b0e1035fb7e32b1c)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging 029eb027b52a9064e95e815aacc7adba8e539e13 into 18ce149682af998683f5f9302af8f1d860fa69bf - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-9f877ede376283f6ea93d6e8f8b3b5d6d13b5780)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bannanc** [comment]
This pull request **introduces 1 alert** when merging 39d72c820b2913d69defba1da8d1940fab5f6413 into 00d0112ecba538051e2fa5a3faef7e8b80d3e818 - [view on LGTM.com](https://lgtm.com/projects/g/MobleyLab/chemper/rev/pr-e87efeb769710e271e8c41a7c1f33e10655931b9)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by j-wags** [comment]
Now I understand why we tried to move this into OFFTK! I think I've resolved the py37 errors by making the `mol_toolkit.Mol` class have the same signature as the `cp_openeye` and `cp_rdkit` mols. 4641e27 does this by providing stubs of the equivalent functions in the `mol_toolkit.Mol` class (and makes it explicitly inherit from `MolAdapter` so changes will track in the future).

 However, I'm a bit nervous about the design pattern where we change `self.__class__` inside the `__init__` function itself (though I do understand why we do it, and wasn't able to think of a good alternative). I've added the following TODO (tl;dr -- We should see if we can make this use OFFMols):

```
    # TODO: This is a really interesting implementation. It basically says "I inherit from MolAdapter, and -- trust me
    #  -- whatever you get out of this will have all the MolAdapter functionality implemented". The class is basically
    #  just a switchboard to figure out which OTHER MolAdapter subclass is appropriate to the input. This design pattern
    #  makes me nervous because it would seem to break a contract with the user, where they call one class's __init__
    #  function, but receive an object of a different class.
    #  Alternatives to this would include
    #       * Having each MolAdapter subclass have a `from_object` method, similar to OFFTK. Then, the MolAdapter
    #         constructor could iterate over all subclasses (using something like an `all_subclasses` method) and
    #         try creating each class from the input, until one succeeds.
    #       * Just use the OFF Molecule class, which avoids this trouble by copying the data OUT of the OEMol or RDMol
    #         into a toolkit-independent format (OFFMol). Then, when manipulation operations occur, the OFFMol is
    #         converted back into the appropriate toolkit molecule, and the operation happens natively there. I think
    #         that smirks_search is the only function that would need to be ported over if that was done.
```

**Comment by j-wags** [comment]
That said, both implementations above are somewhat heavy lifting, and I'm not sure that a refactor is called for at this stage. For now, this works, and that's probably good enough until this gets another full-time maintainer.

**Comment by bannanc** [comment]
For the record, Jeff and I talked and he was going to help get this up to passing so we could merge the PR. I think of the two options above 2 makes more sense (use OFFTK) in the long run, but you have to have access to things like how many hydrogens and what is the connectivity of an atom which right now OFFTK doesn't have. There's no point in heavy lifting to change anything here until someone has done more testing to see if this SMARTS generation is what will ultimately end in the pipeline. 

It looks like Travis is passing now, but Appveyor is failing because it can't get RDKit? I think I followed OFFTK to get Appveyor to work in the first place, but I'm not convinced that window support is necessary at this stage for this tool.

**Comment by j-wags** [comment]
Yeah, sorry, I meant to ask whether Windows support was important to you, @bannanc . It's not critical to me so I'm fine to skip it as well.

I'm happy to give this a quick code review if you think this is ready to go, though I probably won't finish until after the long Thanksgiving weekend. Also, I'm really unfamiliar with this code, so I think it's fine to merge without my input if you think it's ready.

**Comment by bannanc** [comment]
If the travis tests are passing with OE and RDK then I'm fine, but I don't want a failing badge on the README so I think this needs 3 things before I would want to merge:

- [ ] remove Appveyor badge
- [ ] check for any other mention of windows support in the README (I don't think there is)
- [ ] add [ChemPer preprint](https://chemrxiv.org/articles/ChemPer_An_Open_Source_Tool_for_Automatically_Generating_SMIRKS_Patterns/8304578/1) to the references

**Comment by bannanc** [comment]
I'm fine with keeping the Appveyor integration so someone else can fiddle with it in the future, but I don't think its worth the hassle right now.

**Comment by j-wags** [comment]
Sounds good. Let me know if you want my input/help, otherwise I'll stay out of the way :-)

**Comment by bannanc** [comment]
@j-wags do you know why the codecov isn't finished? Is it trying to use the appveyor tests?

**Comment by bannanc** [comment]
Also, I triggered a rebuild on Appveyor to see if that's all it needed

**Comment by bannanc** [comment]
As a quick update, it looks like AppVeyor just needed to be rerun. I'll add the preprint to the README and then merge this branch and cut a release

**Pull request merged**
